## Dataset API

* dataset loaders
    - toy datasets
* dataset fetchers
    - real world datasets

In [ ]:
dataset = {'data': np.array(),
           'target': np.array()}

dataset.data.shape = (n_samples, n_features)
dataset.target.shape = (n_sample,)

dataset.DESCR
dataset.feature_names
dataset.target_names

### Toy datasets

In [5]:
from sklearn import datasets

In [29]:
# boston (Regression)
boston = datasets.load_boston()

print(type(boston))
# print(boston)
# print(boston.data)
# print(boston.target)
print(boston.data.shape)
print(boston.target.shape)
print(boston.feature_names)
print(boston.DESCR)

<class 'sklearn.utils.Bunch'>
(506, 13)
(506,)
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']
Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibilit

In [22]:
# boston (Regression)
boston = datasets.load_boston(return_X_y = True)
print(type(boston))
print(boston[0])
print(boston[1])

<class 'tuple'>
[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]]
[24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19

In [ ]:
# iris (Classification)
iris = datasets.load_iris(return_X_y = False)
print(iris)
print(iris.data)
print(iris.data.shape)
print(iris.target)
print(iris.target.shape)
print(iris.feature_names)
print(iris.target_names)
print(iris.DESCR)


# diabetes (Regression)
diabetes = datasets.load_diabetes(return_X_y = False)
print(diabetes)
print(diabetes.data)
print(diabetes.data.shape)
print(diabetes.target)
print(diabetes.target.shape)


# digits (Classification)
digits = datasets.load_digits()
print(digits)
print(digits.data)
print(digits.data.shape)
print(digits.images)
print(digits.images.shape)
print(digits.target)
print(digits.target.shape)
print(digits.target_names)
print(digits.DESCR)


# linnerud (Multivariable Regression)
linnerud = datasets.load_linnerud()
print(linnerud)
print(linnerud.data)
print(linnerud.data.shape)
print(linnerud.target)
print(linnerud.target.shape)
print(linnerud.feature_names)
print(linnerud.target_names)
print(linnerud.DESCR)


# Wine recognition dataset
wine = datasets.load_wine()


# Breast cancer wisconsin (diagnostic) dataset
diagnostic = datasets.load_breast_cancer()

### Real world dataset

* fetch_olivetti_faces()
* fetch_20newsgroups()
* fetch_20newsgroups_vectorized()
* fetch_lfw_people()
* fetch_lfw_pairs()
* fetch_covtype()
* fetch_rcvl()
* fetch_kddcup99()
* fetch_california_housing()

### 生成数据集

* 分类数据
    - 单个标签
    - 多个标签
    - Biclustering
* 聚类数据
    - 单个标签
    - 多个标签
    - Biclustering
* 回归数据
* manifold learning
* decomposition

#### 分类和聚类数据

* make_blobs
* make_classification
* make_gaussian_quantiles
* make_hastie_10_2
* make_circles
* make_moons
* make_multilabel_classification
* make_biclusters
* make_checkerboard

#### 回归数据

* make_regression
* make_sparse_uncorrelated
* make_friedman1
* make_friedman2
* make_friedman3

#### 流型数据

* make_s_curve
* make_swiss_roll

#### decomposition

* make_low_rank_matrix
* make_sparse_coded_signal
* make_spd_matrix
* make_sparse_spd_matrix

#### 图片样本

* load_sample_images()
* load_sample_image(image_name)

#### svmlight / libsvm 格式

* load_svmlight_file

In [ ]:
from sklearn.datasets import load_svmlight_file

X_train, y_train = load_svmlight_file('/path/to/train_dataset.txt')

X_train, y_train, X_test, y_test = load_svmlight_file(("/path/to/train_dataset.txt", 
                                                       "/path/to/test_dataset.txt"))

X_test, y_test = load_svmlight_file('/path/to/test_dataset.txt', 
                                    n_features = X_train.shape[1])

#### 下载openml.org repository中的数据

* [openml.org](https://openml.org/)
* `sklearn.datasets.fetch_openml`

In [ ]:
from sklearn.datasets import fetch_openml

mice = fetch_openml(name = 'miceprotein', version = 4)

print(mice.data.shape)
print(mice.target.shape)
print(np.unique(mice.target))
print(mice.DESCR)
print(mice.details)
print(mice.details['version'])
print(mice.details['id'])
print(mice.url)


mice = fetch_openml(data_id = 40966)
print(mice.details)
print(mice.details['version'])

#### 外部数据

* pandas.io
* scipy.io
* numpy / routines.io
* skimage.io
* Imageio
* sicpy.io.wavfile.read
* sklearn.preprocessing.OneHotEncoder
* sklearn.preprocessing.OrdinalEncoder