In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline
# plt.rcParams

# IPython 魔法命令

# Pandas

## Series

### Series basic

In [2]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [3]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [4]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [5]:
data[0]

0.25

In [15]:
data[0:3]

a    0.25
b    0.50
c    0.75
dtype: float64

### Series Numpy 数组

In [17]:
# 显示定义的索引与数值关联
data = pd.Series(
    [0.25, 0.5, 0.75, 1.0],
    index = ["a", "b", "c", "d"]
)
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [18]:
data.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [19]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [20]:
data["a"]

0.25

In [21]:
data[0]

0.25

In [22]:
data["a":"c"]

a    0.25
b    0.50
c    0.75
dtype: float64

In [23]:
data[0:3]

a    0.25
b    0.50
c    0.75
dtype: float64

In [24]:
# 不连续或不按顺序的索引
data = pd.Series(
    [0.25, 0.5, 0.75, 1.0],
    index = [2, 5, 3, 7],
)
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [25]:
data[5]

0.5

### Series 特殊字典

In [26]:
population_dict = {
    'California': 38332521,
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135
}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [27]:
population.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [28]:
population.values

array([38332521, 26448193, 19651127, 19552860, 12882135], dtype=int64)

In [33]:
print(population.name)

None


In [34]:
population.dtype

dtype('int64')

In [35]:
population["California"]

38332521

In [36]:
population["California":"Florida"]

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
dtype: int64

### Series 创建

In [38]:
pd.Series(data = [2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [39]:
pd.Series(5, index = [100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [40]:
pd.Series({
    2: "a",
    1: "b",
    3: "c",
})

2    a
1    b
3    c
dtype: object

In [42]:
# 通过显式指定索引筛选结果
pd.Series({
    2: "a",
    1: "b",
    3: "c",
}, index = [3, 2])

3    c
2    a
dtype: object

## DataFrame

### DataFrame Numpy 数组

In [44]:
population_dict = {
    'California': 38332521,
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135
}
population = pd.Series(population_dict)

area_dict = {
    'California': 423967, 
    'Texas': 695662, 
    'New York': 141297,
    'Florida': 170312, 
    'Illinois': 149995
}
area = pd.Series(area_dict)

states = pd.DataFrame({
    "population": population,
    "area": area,
})
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [45]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [46]:
states.columns

Index(['population', 'area'], dtype='object')

### DataFrame 特殊字典

In [47]:
states

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [48]:
states["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [49]:
states["population"]

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: population, dtype: int64

### DataFrame 创建

In [53]:
df = pd.DataFrame(population, columns = ["poopulation"])
df

poopulation
California     38332521
Texas          26448193
New York       19651127
Florida        19552860
Illinois       12882135

In [56]:
d = [{
    "a": i,
    "b": 2 * i
} for i in range(3)]
print(d)

df = pd.DataFrame(d)
df

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]


a  b
0  0  0
1  1  2
2  2  4

In [59]:
d = {
    "a": [i for i in range(3)],
    "b": [i * 2 for i in range(3)]
}
print(d)
df = pd.DataFrame(d)
df

{'a': [0, 1, 2], 'b': [0, 2, 4]}


a  b
0  0  0
1  1  2
2  2  4

In [57]:
df = pd.DataFrame({
    "population": population,
    "area": area,
})
df

population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

In [61]:
df = pd.DataFrame(
    data = np.random.rand(3, 2),
    columns = ["foo", "bar"],
    index = ["a", "b", "c"],
)
df

foo       bar
a  0.193998  0.684546
b  0.479851  0.401493
c  0.267337  0.460016

In [66]:
A = np.zeros(3, dtype = [("A", "i8"), ("B", "f8")])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [67]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## Index

### Index 不可变数组

In [6]:
# 整数列表创建 Index 对象
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [5]:
# 索引
ind[1]

3

In [7]:
# 切片
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [8]:
# Index 属性
print(ind.size)
print(ind.ndim)
print(ind.dtype)

5
1
int64


In [10]:
# Index 对象的索引是不可变的
ind[1] = 0

TypeError: Index does not support mutable operations

### Index 有序集合

In [11]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])

In [12]:
# 集合操作：交集
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

In [13]:
# 集合操作：并集
indA.union(indB)

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [15]:
# 集合操作：异或
indA.symmetric_difference(indB)

Int64Index([1, 2, 9, 11], dtype='int64')

## 数据取值与选择

### Series

#### Series 字典

In [2]:
data = pd.Series(
    [0.25, 0.5, 0.75, 1.0],
    index = ["a", "b", "c", "d"]
)
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [7]:
print(data.index)
print(data.values)

Index(['a', 'b', 'c', 'd'], dtype='object')
[0.25 0.5  0.75 1.  ]


In [3]:
data["b"]

0.5

In [4]:
"a" in data

True

In [5]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [8]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [11]:
data["e"] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

#### Series 一维数组

In [21]:
# 显式索引(包含最后一个索引)
data["a":"c"]

a    0.25
b    0.50
c    0.75
dtype: float64

In [22]:
# 隐式索引(不包含最后一个索引)
data[0:3]

a    0.25
b    0.50
c    0.75
dtype: float64

In [19]:
# 掩码
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [20]:
# 花哨的索引
data[["a", "e"]]

a    0.25
e    1.25
dtype: float64

#### Series 索引器

In [27]:
data = pd.Series(
    ["a", "b", "c", "d"], 
    index = [1, 3, 5, 7],
)
data

1    a
3    b
5    c
7    d
dtype: object

In [37]:
# 显式索引
print(data[1])
print()
# 隐式索引
print(data[1:3])

a

3    b
5    c
dtype: object


In [38]:
# loc 属性，取值和切片都是显式的
print(data.loc[1])
print()
print(data.loc[1:3])

a

1    a
3    b
dtype: object


In [39]:
# iloc 属性，取值和切片都是隐式索引
print(data.iloc[1])
print()
print(data.iloc[1:3])

b

3    b
5    c
dtype: object


### DataFrame

#### DataFrame 字典

In [40]:
area = pd.Series({
    'California': 423967, 
    'Texas': 695662,
    'New York': 141297, 
    'Florida': 170312,
    'Illinois': 149995
})
pop = pd.Series({
    'California': 38332521, 
    'Texas': 26448193,
    'New York': 19651127, 
    'Florida': 19552860,
    'Illinois': 12882135
})
data = pd.DataFrame({
    'area':area, 
    'pop':pop
})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [41]:
data["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [42]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [43]:
data["area"] is data.area

True

In [45]:
data.pop is data["pop"]

False

In [46]:
data["density"] = data["pop"] / data["area"]
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

#### DataFrame 二维数组

In [54]:
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [47]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [48]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [56]:
# 获取一行数据
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [57]:
# 获取一列
data["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [65]:
# 显式索引
data.loc[:"New York", :"pop"]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [66]:
# 隐式索引
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [69]:
# loc 索引器中结合使用掩码与花哨的索引方法
data.loc[data.density > 100, ["pop", "density"]]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [70]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

#### 其他

In [78]:
# 对多个标签用切片选择行
# 显示索引，包含最后一个索引
data["Florida":"Illinois"]

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [79]:
# 显示索引，不包含最后一个索引
data[3:5]

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [80]:
# 掩码
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

In [87]:
# 对单个标签取值选择列
data["area"]

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64