In [3]:
import numpy as np

from sklearn.datasets import load_boston
# from future_encoders import ColumnTransformer
from sklearn.compose import TransformedTargetRegressor

from sklearn import preprocessing
from sklearn.preprocessing import QuantileTransformer

from sklearn.linear_model import LinearRegression

from sklearn.model_selection import train_test_split

ModuleNotFoundError: No module named 'sklearn.compose'

### Label binarization

In [24]:
y = [1, 2, 6, 4, 2]

lb = preprocessing.LabelBinarizer()
lb.fit(y)

print(lb.classes_)
print()
print(lb.transform([1, 2, 4, 6]))

[1 2 4 6]

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [25]:
y = [(1, 2), (3, )]

lb = preprocessing.MultiLabelBinarizer()
lb.fit(y)

print(lb.classes_)
print(lb.transform([(1, 2), (3, )]))

[1 2 3]
[[1 1 0]
 [0 0 1]]


### Label encoding

In [15]:
y = [1, 2, 2, 6]

le = preprocessing.LabelEncoder()
le.fit(y)

print(le.classes_)
print(le.transform([1, 1, 2, 6]))
print(le.inverse_transform([0, 0, 1, 2]))

[1 2 6]
[0 0 1 2]
[1 1 2 6]


E:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:


In [18]:
y = ['paris', 'paris', 'tokyo', 'amsterdam']

le = preprocessing.LabelEncoder()
le.fit(y)

print(le.classes_)
print(le.transform(['tokyo', 'tokyo', 'paris']))
print(list(le.inverse_transform([2, 2, 1])))

['amsterdam' 'paris' 'tokyo']
[2 2 1]
['tokyo', 'tokyo', 'paris']


E:\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:
