In [2]:
import numpy as np
import pandas as pd

In [3]:
print(np.__version__)
print(pd.__version__)

1.16.2
0.24.2


## 1. pd.Series()

In [4]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [5]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [6]:
data.value_counts()

1.00    1
0.75    1
0.50    1
0.25    1
dtype: int64

In [7]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [8]:
data[1]

0.5

In [9]:
data[1:3]

1    0.50
2    0.75
dtype: float64

In [10]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [11]:
data['b']

0.5

In [12]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = [2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [13]:
data[5]

0.5

In [14]:
population_dict = {'California': 38332521,
                   'Texas': 2324234,
                   'New York': 3423423423,
                   'Florida': 2433424234,
                   'Illinois': 442343242}
population = pd.Series(population_dict)
population

California      38332521
Texas            2324234
New York      3423423423
Florida       2433424234
Illinois       442343242
dtype: int64

In [15]:
population['California']

38332521

In [16]:
population['California':'New York']

California      38332521
Texas            2324234
New York      3423423423
dtype: int64

In [17]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

In [18]:
pd.Series(5, index = [100, 200, 300])

100    5
200    5
300    5
dtype: int64

In [19]:
pd.Series({2: 'a', 1: 'b', 3: 'c'})

2    a
1    b
3    c
dtype: object

In [20]:
pd.Series({2: 'a', 1: 'b', 3: 'c'}, index = [3, 2])

3    c
2    a
dtype: object

## 2. pd.DataFrame()

In [21]:
area_dict = {'California': 3424234, 'Texas': 434234, 'New York': 423423, 'Florida': 423423, 'Illinois': 423423}
area = pd.Series(area_dict)
area

California    3424234
Texas          434234
New York       423423
Florida        423423
Illinois       423423
dtype: int64

In [22]:
states = pd.DataFrame({'population': population, 
                       'area': area})
states

population     area
California    38332521  3424234
Texas          2324234   434234
New York    3423423423   423423
Florida     2433424234   423423
Illinois     442343242   423423

In [23]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

In [24]:
states.columns

Index(['population', 'area'], dtype='object')

In [25]:
states.values

array([[  38332521,    3424234],
       [   2324234,     434234],
       [3423423423,     423423],
       [2433424234,     423423],
       [ 442343242,     423423]], dtype=int64)

In [26]:
states['area']

California    3424234
Texas          434234
New York       423423
Florida        423423
Illinois       423423
Name: area, dtype: int64

In [27]:
population

California      38332521
Texas            2324234
New York      3423423423
Florida       2433424234
Illinois       442343242
dtype: int64

In [28]:
type(population)

pandas.core.series.Series

In [29]:
pd.DataFrame(population, columns = ['population'])

population
California    38332521
Texas          2324234
New York    3423423423
Florida     2433424234
Illinois     442343242

In [30]:
data = [{'a': i, 'b': 2*i} for i in range(3)]
data

[{'a': 0, 'b': 0}, {'a': 1, 'b': 2}, {'a': 2, 'b': 4}]

In [31]:
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [32]:
pd.DataFrame([{'a': 1, 'b':2}, {'b': 3, 'c': 4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [33]:
pd.DataFrame({'population': population, 'area': area})

population     area
California    38332521  3424234
Texas          2324234   434234
New York    3423423423   423423
Florida     2433424234   423423
Illinois     442343242   423423

In [34]:
pd.DataFrame(np.random.randint(1, 10, (3, 2)), columns = ['foo', 'bar'], index = ['a', 'b', 'c'])

foo  bar
a    2    4
b    9    6
c    5    7

In [35]:
A = np.zeros(3, dtype = [('A', 'i8'), ('B', 'f8')])
A

array([(0, 0.), (0, 0.), (0, 0.)], dtype=[('A', '<i8'), ('B', '<f8')])

In [36]:
pd.DataFrame(A)

A    B
0  0  0.0
1  0  0.0
2  0  0.0

## 3. pd.Index()

In [37]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [38]:
ind[1]

3

In [39]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [40]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


In [41]:
indA = pd.Index([1, 3, 5, 7, 9])
indB = pd.Index([2, 3, 5, 7, 11])
indA & indB

Int64Index([3, 5, 7], dtype='int64')

In [42]:
indA | indB

Int64Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [43]:
indA ^ indB

Int64Index([1, 2, 9, 11], dtype='int64')

In [44]:
indA.intersection(indB)

Int64Index([3, 5, 7], dtype='int64')

# 3. 数据取值与选择

In [45]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index = ['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [46]:
data['b']

0.5

In [47]:
'a' in data

True

In [48]:
data.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [49]:
list(data.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

In [50]:
data['e'] = 1.25
data

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [51]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [52]:
data[0:2]

a    0.25
b    0.50
dtype: float64

In [53]:
data[(data > 0.3) & (data < 0.8)]

b    0.50
c    0.75
dtype: float64

In [54]:
data[['a', 'e']]

a    0.25
e    1.25
dtype: float64

In [55]:
data = pd.Series(['a', 'b', 'c', 'd'], index = [3, 2, 1, 4])
data

3    a
2    b
1    c
4    d
dtype: object

In [56]:
data[1]

'c'

In [57]:
data[1:3]

2    b
1    c
dtype: object

In [58]:
data.loc[1]

'c'

In [59]:
data.loc[1:4]

1    c
4    d
dtype: object

In [60]:
data.iloc[1]

'b'

In [61]:
data.iloc[1:3]

2    b
1    c
dtype: object

In [62]:
area = pd.Series({'California': 423967, 
                  'Texas': 695662,
                  'New York': 141297, 
                  'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 
                 'Texas': 26448193,
                 'New York': 19651127, 
                 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

In [63]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [64]:
data.area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [65]:
data['area'] is data.area

True

In [66]:
data.pop

<bound method NDFrame.pop of               area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135>

In [67]:
data['pop']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

In [68]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California  423967  38332521   90.413926
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [69]:
data.values

array([[4.23967000e+05, 3.83325210e+07, 9.04139261e+01],
       [6.95662000e+05, 2.64481930e+07, 3.80187404e+01],
       [1.41297000e+05, 1.96511270e+07, 1.39076746e+02],
       [1.70312000e+05, 1.95528600e+07, 1.14806121e+02],
       [1.49995000e+05, 1.28821350e+07, 8.58837628e+01]])

In [70]:
data.T

California         Texas      New York       Florida      Illinois
area     4.239670e+05  6.956620e+05  1.412970e+05  1.703120e+05  1.499950e+05
pop      3.833252e+07  2.644819e+07  1.965113e+07  1.955286e+07  1.288214e+07
density  9.041393e+01  3.801874e+01  1.390767e+02  1.148061e+02  8.588376e+01

In [71]:
data.values[0]

array([4.23967000e+05, 3.83325210e+07, 9.04139261e+01])

In [72]:
data.T.California

area       4.239670e+05
pop        3.833252e+07
density    9.041393e+01
Name: California, dtype: float64

In [73]:
data.iloc[:3, :2]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [74]:
data[['area', 'density']]

area     density
California  423967   90.413926
Texas       695662   38.018740
New York    141297  139.076746
Florida     170312  114.806121
Illinois    149995   85.883763

In [75]:
data.loc[:'Florida', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860

In [76]:
data.ix[:3, :'pop']

D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

In [77]:
data.loc[data.density > 100, ['pop', 'density']]

pop     density
New York  19651127  139.076746
Florida   19552860  114.806121

In [78]:
data.iloc[0, 2] = 90
data

area       pop     density
California  423967  38332521   90.000000
Texas       695662  26448193   38.018740
New York    141297  19651127  139.076746
Florida     170312  19552860  114.806121
Illinois    149995  12882135   85.883763

In [79]:
# 选择列
data['area'] 
# data['California']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

In [80]:
# 选择行
data['Florida':'Illinois']
# data['area':'pop']

area       pop     density
Florida   170312  19552860  114.806121
Illinois  149995  12882135   85.883763

In [81]:
# 选择行
data[1:3]

area       pop     density
Texas     695662  26448193   38.018740
New York  141297  19651127  139.076746

In [82]:
# 选择行
data[data.density > 100]

area       pop     density
New York  141297  19651127  139.076746
Florida   170312  19552860  114.806121

# 4. 数值运算方法

In [83]:
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0, 10, 4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [84]:
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns = ['A', 'B', 'C', 'D'])
df

A  B  C  D
0  6  9  2  6
1  7  4  3  7
2  7  2  5  4

In [85]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [86]:
np.sin(df * np.pi / 4)

A             B         C             D
0 -1.000000  7.071068e-01  1.000000 -1.000000e+00
1 -0.707107  1.224647e-16  0.707107 -7.071068e-01
2 -0.707107  1.000000e+00 -0.707107  1.224647e-16

In [87]:
area = pd.Series({'Alaska': 1723337, 
                  'Texas': 695662,
                  'California': 423967}, name='area')
population = pd.Series({'California': 38332521,
                        'Texas': 26448193,
                        'New York': 19651127}, name='population')
population / area

Alaska              NaN
California    90.413926
New York            NaN
Texas         38.018740
dtype: float64

In [88]:
area.index | population.index

Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [89]:
A = pd.Series([2, 4, 6], index=[0, 1, 2])
B = pd.Series([1, 3, 5], index=[1, 2, 3])
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [90]:
A.add(B, fill_value = 0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [91]:
A.sub(B, fill_value = 0)

0    2.0
1    3.0
2    3.0
3   -5.0
dtype: float64

In [92]:
A.subtract(B, fill_value = 0)

0    2.0
1    3.0
2    3.0
3   -5.0
dtype: float64

In [93]:
A.mul(B, fill_value = 0)

0     0.0
1     4.0
2    18.0
3     0.0
dtype: float64

In [94]:
A.multiply(B, fill_value = 0)

0     0.0
1     4.0
2    18.0
3     0.0
dtype: float64

In [95]:
A.truediv(B, fill_value = 0)

0         inf
1    4.000000
2    2.000000
3    0.000000
dtype: float64

In [96]:
A.div(B, fill_value = 0)

0         inf
1    4.000000
2    2.000000
3    0.000000
dtype: float64

In [97]:
A.divide(B)

0    NaN
1    4.0
2    2.0
3    NaN
dtype: float64

In [98]:
A.floordiv(B)

0    NaN
1    4.0
2    2.0
3    NaN
dtype: float64

In [99]:
A.mod(B)

0    NaN
1    0.0
2    0.0
3    NaN
dtype: float64

In [100]:
A.pow(B)

0      NaN
1      4.0
2    216.0
3      NaN
dtype: float64

In [101]:
rng = np.random.RandomState(42)
A = pd.DataFrame(rng.randint(0, 20, (2, 2)),
                 columns = list('AB'))
A

A   B
0   6  19
1  14  10

In [102]:
B = pd.DataFrame(rng.randint(0, 10, (3, 3)),
                 columns = list('BAC'))
B

B  A  C
0  7  4  6
1  9  2  6
2  7  4  3

In [103]:
A + B

A     B   C
0  10.0  26.0 NaN
1  16.0  19.0 NaN
2   NaN   NaN NaN

In [104]:
fill = A.stack().mean()
fill

12.25

In [105]:
A.add(B, fill_value = fill)

A      B      C
0  10.00  26.00  18.25
1  16.00  19.00  18.25
2  16.25  19.25  15.25

In [106]:
A = rng.randint(10, size= (3, 4))
A

array([[7, 7, 2, 5],
       [4, 1, 7, 5],
       [1, 4, 0, 9]])

In [107]:
A - A[0]

array([[ 0,  0,  0,  0],
       [-3, -6,  5,  0],
       [-6, -3, -2,  4]])

In [108]:
df = pd.DataFrame(A, columns = list('QRST'))
df 

Q  R  S  T
0  7  7  2  5
1  4  1  7  5
2  1  4  0  9

In [109]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -3 -6  5  0
2 -6 -3 -2  4

In [110]:
df.subtract(df['R'], axis = 0)

Q  R  S  T
0  0  0 -5 -2
1  3  0  6  4
2 -3  0 -4  5

In [111]:
halfrow = df.iloc[0, ::2]
halfrow

Q    7
S    2
Name: 0, dtype: int32

In [112]:
df - halfrow

Q   R    S   T
0  0.0 NaN  0.0 NaN
1 -3.0 NaN  5.0 NaN
2 -6.0 NaN -2.0 NaN

## 5.缺失值处理

In [113]:
vals1 = np.array([1, None, 3, 4])
vals1

array([1, None, 3, 4], dtype=object)

In [114]:
for dtype in ['object', 'int']:
    print("dtype = ", dtype)
    %timeit np.arange(1E6, dtype = dtype).sum()
    print()

dtype =  object
235 ms ± 18.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

dtype =  int
5.89 ms ± 751 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)



In [115]:
# vals1.sum()

In [116]:
vals2 = np.array([1, np.nan, 3, 4])
vals2

array([ 1., nan,  3.,  4.])

In [117]:
vals2.dtype

dtype('float64')

In [118]:
1 + np.nan

nan

In [119]:
0 * np.nan

nan

In [120]:
vals2.sum(), vals2.max(), vals2.min()

D:\Anaconda3\lib\site-packages\numpy\core\_methods.py:28: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial)
D:\Anaconda3\lib\site-packages\numpy\core\_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial)


(nan, nan, nan)

In [121]:
np.nansum(vals2), np.nanmax(vals2), np.nanmin(vals2)

(8.0, 4.0, 1.0)

In [122]:
pd.Series([1, np.nan, 3, 4])

0    1.0
1    NaN
2    3.0
3    4.0
dtype: float64

In [123]:
x = pd.Series(range(2), dtype = int)
x

0    0
1    1
dtype: int32

In [124]:
x[0] = np.nan
x

0    NaN
1    1.0
dtype: float64

In [125]:
data = pd.Series([1, np.nan, 'hello', None])
data

0        1
1      NaN
2    hello
3     None
dtype: object

In [126]:
data.isnull()

0    False
1     True
2    False
3     True
dtype: bool

In [127]:
data.notnull()

0     True
1    False
2     True
3    False
dtype: bool

In [128]:
data[data.notnull()]

0        1
2    hello
dtype: object

In [129]:
data.dropna()

0        1
2    hello
dtype: object

In [130]:
df = pd.DataFrame([[1, np.nan, 2], 
                   [2, 3, 5],
                   [np.nan, 4, 6]])
df

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [131]:
df.dropna()

0    1  2
1  2.0  3.0  5

In [132]:
df.dropna(axis = 1)

2
0  2
1  5
2  6

In [133]:
df.dropna(axis = 'columns')

2
0  2
1  5
2  6

In [134]:
df.dropna(axis = 0)

0    1  2
1  2.0  3.0  5

In [135]:
df.dropna(axis = 'rows')

0    1  2
1  2.0  3.0  5

In [136]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [137]:
df.dropna(axis = 'columns', how = 'all')

0    1  2
0  1.0  NaN  2
1  2.0  3.0  5
2  NaN  4.0  6

In [138]:
df.dropna(axis = "columns", how = 'any')

2
0  2
1  5
2  6

In [139]:
df.dropna(axis = 'rows', thresh = 3)

0    1  2   3
1  2.0  3.0  5 NaN

In [140]:
data = pd.Series([1, np.nan, 2, None, 3], index = list('abcde'))
data

a    1.0
b    NaN
c    2.0
d    NaN
e    3.0
dtype: float64

In [141]:
data.fillna(0)

a    1.0
b    0.0
c    2.0
d    0.0
e    3.0
dtype: float64

In [142]:
data.fillna(method = 'ffill')

a    1.0
b    1.0
c    2.0
d    2.0
e    3.0
dtype: float64

In [143]:
data.fillna(method = 'bfill')

a    1.0
b    2.0
c    2.0
d    3.0
e    3.0
dtype: float64

In [144]:
df[3] = np.nan
df

0    1  2   3
0  1.0  NaN  2 NaN
1  2.0  3.0  5 NaN
2  NaN  4.0  6 NaN

In [145]:
df.fillna(method = 'ffill', axis = 1)

0    1    2    3
0  1.0  1.0  2.0  2.0
1  2.0  3.0  5.0  5.0
2  NaN  4.0  6.0  6.0

# 6.层级索引

In [146]:
index = [('California', 2000), 
         ('California',  2010), 
         ('New York', 2000), 
         ('New York', 2010), 
         ('Texas', 2000), 
         ('Texas', 2010)]
populations = [33871648, 
               37253956, 
               18976457, 
               19378102, 
               20851820, 
               25145561]
pop = pd.Series(populations, index = index)
pop

(California, 2000)    33871648
(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
(Texas, 2010)         25145561
dtype: int64

In [147]:
pop[('California', 2010):('Texas', 2000)]

(California, 2010)    37253956
(New York, 2000)      18976457
(New York, 2010)      19378102
(Texas, 2000)         20851820
dtype: int64

In [148]:
pop[[i for i in pop.index if i[1] == 2010]]

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [149]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex(levels=[['California', 'New York', 'Texas'], [2000, 2010]],
           labels=[[0, 0, 1, 1, 2, 2], [0, 1, 0, 1, 0, 1]])

In [150]:
pop = pop.reindex(index)
pop

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [151]:
pop[:, 2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [152]:
pop.unstack()

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [153]:
# pop_df.stack()

In [154]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094, 4687374, 4318033, 5906301, 6879014]})
pop_df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [155]:
f_u18 = pop_df['under18'] / pop_df['total']
f_u18

California  2000    0.273594
            2010    0.249211
New York    2000    0.247010
            2010    0.222831
Texas       2000    0.283251
            2010    0.273568
dtype: float64

In [156]:
f_u18.unstack()

2000      2010
California  0.273594  0.249211
New York    0.247010  0.222831
Texas       0.283251  0.273568

In [157]:
df = pd.DataFrame(np.random.rand(4, 2),
                  index = [['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns = ['data1', 'data2'])
df

data1     data2
a 1  0.048825  0.845154
  2  0.472443  0.210683
b 1  0.569952  0.202335
  2  0.648955  0.317103

In [158]:
data = {('California', 2000): 33871648,
        ('California', 2010): 37253956,
        ('Texas', 2000): 20851820,
        ('Texas', 2010): 25145561,
        ('New York', 2000): 18976457,
        ('New York', 2010): 19378102}
pd.Series(data)

California  2000    33871648
            2010    37253956
Texas       2000    20851820
            2010    25145561
New York    2000    18976457
            2010    19378102
dtype: int64

## 合并数据集：concat, append, merge

In [159]:
import numpy as np
import pandas as pd

In [160]:
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind] for c in cols}
    return pd.DataFrame(data, ind)

make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [161]:
x = [1, 2, 3]
y = [4, 5, 6]
z = [7, 8, 9]
np.concatenate([x, y, z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [162]:
x = [[1, 2], [3, 4]]
np.concatenate([x, x], axis = 1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

> pd.concat(objs, axis=0, join='outer', join_axes=None, ignore_index=False, keys=None, levels=None, names=None, verify_integrity=False,copy=True)

In [163]:
ser1 = pd.Series(['A', 'B', 'C'], index = [1, 2, 3])
ser2 = pd.Series(['D', 'E', 'F'], index = [4, 5, 6])
pd.concat([ser1, ser2])

1    A
2    B
3    C
4    D
5    E
6    F
dtype: object

In [164]:
df1 = make_df('AB', [1, 2])
df2 = make_df('AB', [3, 4])
print(df1); print(df2); print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [165]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])
print(df3); print(df4); print(pd.concat([df3, df4], axis = 1))

    A   B
0  A0  B0
1  A1  B1
    C   D
0  C0  D0
1  C1  D1
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1


In [166]:
x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])
y.index = x.index # 复制索引
print(x); print(y); print(pd.concat([x, y]))

    A   B
0  A0  B0
1  A1  B1
    A   B
0  A2  B2
1  A3  B3
    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3


In [167]:
try:
    pd.concat([x, y], verify_integrity = False)
except ValueError as e:
    print("ValueError:", e)

In [168]:
pd.concat([x, y], ignore_index = True)

A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [169]:
pd.concat([x, y], keys = ['x', 'y'])

A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3

In [170]:
df5 = make_df('ABC', [1, 2])
df6 = make_df('BCD', [3, 4])
print(df5); print(df6), print(pd.concat([df5, df6]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  This is separate from the ipykernel package so we can avoid doing imports until


(None, None)

In [171]:
pd.concat([df5, df6], join = 'outer', sort = False)

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4

In [172]:
pd.concat([df5, df6], join = 'inner')

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4

In [173]:
pd.concat([df5, df6], join_axes = [df5.columns])

A   B   C
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4

In [174]:
pd.concat([df5, df6], join_axes = [df6.columns])

B   C    D
1  B1  C1  NaN
2  B2  C2  NaN
3  B3  C3   D3
4  B4  C4   D4

In [175]:
print(df1); print(df2); print(df1.append(df2))

    A   B
1  A1  B1
2  A2  B2
    A   B
3  A3  B3
4  A4  B4
    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [176]:
pd.concat([df1, df2], axis = 1)
# df1.append(df2, axis = 1) # 不能运行

A    B    A    B
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3  NaN  NaN   A3   B3
4  NaN  NaN   A4   B4

In [177]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})
df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]})
print(df1); print(df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014


In [178]:
df3 = pd.merge(df1, df2)
print(df3)

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014


In [179]:
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})
print(df4)

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve


In [180]:
pd.merge(df3, df4)

employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [181]:
df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                    'Engineering', 'Engineering', 'HR', 'HR'],
                    'skills': ['math', 'spreadsheets', 'coding', 'linux',
                    'spreadsheets', 'organization']})
print(df5)
print(df1)

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization
  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR


In [182]:
pd.merge(df1, df5)

employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [183]:
pd.merge(df1, df2, on = 'employee')

employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [184]:
df3 = pd.DataFrame({'name': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'salary': [70000, 80000, 120000, 90000]})
print(df1); print(df3)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000


In [185]:
pd.merge(df1, df3, left_on = 'employee', right_on = 'name')

employee        group  name  salary
0      Bob   Accounting   Bob   70000
1     Jake  Engineering  Jake   80000
2     Lisa  Engineering  Lisa  120000
3      Sue           HR   Sue   90000

In [186]:
pd.merge(df1, df3, left_on = 'employee', right_on = 'name').drop('name', axis = 1)

employee        group  salary
0      Bob   Accounting   70000
1     Jake  Engineering   80000
2     Lisa  Engineering  120000
3      Sue           HR   90000

## 数据透视表 pivot_table()

In [187]:
import numpy as np
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [188]:
titanic.groupby('sex')[['survived']].mean()

survived
sex             
female  0.742038
male    0.188908

In [189]:
titanic.groupby(['sex', 'class'])['survived'].aggregate('mean').unstack()

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [190]:
titanic.groupby(['sex', 'class'])['survived'].mean().unstack()

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [191]:
titanic.pivot_table('survived', index = 'sex', columns = 'class') 

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [192]:
age = pd.cut(titanic['age'], [0, 18, 80])
titanic.pivot_table('survived', index = ['sex', age], columns = 'class')

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 80]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 80]  0.375000  0.071429  0.133663

In [193]:
fare = pd.qcut(titanic['fare'], 2)
titanic.pivot_table('survived', index = ['sex', age], columns = [fare, 'class'])

fare            (-0.001, 14.454]                     (14.454, 512.329]  \
class                      First    Second     Third             First   
sex    age                                                               
female (0, 18]               NaN  1.000000  0.714286          0.909091   
       (18, 80]              NaN  0.880000  0.444444          0.972973   
male   (0, 18]               NaN  0.000000  0.260870          0.800000   
       (18, 80]              0.0  0.098039  0.125000          0.391304   

fare                                 
class              Second     Third  
sex    age                           
female (0, 18]   1.000000  0.318182  
       (18, 80]  0.914286  0.391304  
male   (0, 18]   0.818182  0.178571  
       (18, 80]  0.030303  0.192308

Pandas 0.18版的函数签名

> DataFrame.pivot_table(data, values=None, index=None, columns=None, aggfunc='mean', fill_value=None, margins=False, dropna=True, margins_name='All')

In [194]:
titanic.pivot_table(index = 'sex', columns = 'class', aggfunc = {'survived': 'sum', 'fare': 'mean'})

fare                       survived             
class        First     Second      Third    First Second Third
sex                                                           
female  106.125798  21.970121  16.118810       91     70    72
male     67.226127  19.741782  12.661633       45     17    47

In [195]:
titanic.pivot_table('survived', index = 'sex', columns = 'class', margins = True)

class      First    Second     Third       All
sex                                           
female  0.968085  0.921053  0.500000  0.742038
male    0.368852  0.157407  0.135447  0.188908
All     0.629630  0.472826  0.242363  0.383838

### Pandas日期，时间

In [196]:
from datetime import datetime

In [197]:
datetime(year = 2018, month = 12, day = 4)

datetime.datetime(2018, 12, 4, 0, 0)

In [198]:
from dateutil import parser

In [199]:
date = parser.parse("4th of July, 2018")
date

datetime.datetime(2018, 7, 4, 0, 0)

In [200]:
date.strftime('%A')

'Wednesday'

In [201]:
import pytz

In [202]:
import numpy as np
date = np.array('2018-12-08', dtype = np.datetime64)
date

array('2018-12-08', dtype='datetime64[D]')

In [203]:
date + np.arange(12)

array(['2018-12-08', '2018-12-09', '2018-12-10', '2018-12-11',
       '2018-12-12', '2018-12-13', '2018-12-14', '2018-12-15',
       '2018-12-16', '2018-12-17', '2018-12-18', '2018-12-19'],
      dtype='datetime64[D]')

In [204]:
np.datetime64('2018-12-08')

numpy.datetime64('2018-12-08')

In [205]:
np.datetime64('2018-12-08 12:00')

numpy.datetime64('2018-12-08T12:00')

In [206]:
np.datetime64('2018-12-08 12:59:59.50', 'ns')

numpy.datetime64('2018-12-08T12:59:59.500000000')

In [207]:
import pandas as pd
date = pd.to_datetime('4th of July, 2018')
date

Timestamp('2018-07-04 00:00:00')

In [208]:
date.strftime('%A')

'Wednesday'

In [209]:
date + pd.to_timedelta(np.arange(12), 'D')

DatetimeIndex(['2018-07-04', '2018-07-05', '2018-07-06', '2018-07-07',
               '2018-07-08', '2018-07-09', '2018-07-10', '2018-07-11',
               '2018-07-12', '2018-07-13', '2018-07-14', '2018-07-15'],
              dtype='datetime64[ns]', freq=None)

In [210]:
index = pd.DatetimeIndex(['2014-07-04', '2014-08-04', '2015-07-04', '2015-08-04'])
data = pd.Series([0, 1, 2, 3], index = index)
data

2014-07-04    0
2014-08-04    1
2015-07-04    2
2015-08-04    3
dtype: int64

In [211]:
data['2014-07-04':'2015-07-04']

2014-07-04    0
2014-08-04    1
2015-07-04    2
dtype: int64

In [212]:
data['2015']

2015-07-04    2
2015-08-04    3
dtype: int64

|时间序列数据类|时间序列索引类|
|--------------|--------------|
|Timestamp|DatetimeIndex
|Period|PeriodIndex
|Timedelta|TimedeltaIndex

In [213]:
dates = pd.to_datetime([datetime(2015, 7, 3), '4th of July, 2015', '2015-Jul-6', '07-07-2015', '20150708'])
dates

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-06', '2015-07-07',
               '2015-07-08'],
              dtype='datetime64[ns]', freq=None)

In [214]:
dates.to_period("D")

PeriodIndex(['2015-07-03', '2015-07-04', '2015-07-06', '2015-07-07',
             '2015-07-08'],
            dtype='period[D]', freq='D')

In [215]:
dates - dates[0]

TimedeltaIndex(['0 days', '1 days', '3 days', '4 days', '5 days'], dtype='timedelta64[ns]', freq=None)

|方法|作用|
|----|----|
|pd.date_range()|处理时间戳
|pd.period_range()|处理周期
|pd.timedelta_range()|处理时间间隔

In [216]:
pd.date_range('2015-07-03', '2015-07-10')

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [217]:
pd.date_range('2015-07-03', periods = 8)

DatetimeIndex(['2015-07-03', '2015-07-04', '2015-07-05', '2015-07-06',
               '2015-07-07', '2015-07-08', '2015-07-09', '2015-07-10'],
              dtype='datetime64[ns]', freq='D')

In [218]:
pd.date_range('2015-07-03', periods = 8, freq = 'H')

DatetimeIndex(['2015-07-03 00:00:00', '2015-07-03 01:00:00',
               '2015-07-03 02:00:00', '2015-07-03 03:00:00',
               '2015-07-03 04:00:00', '2015-07-03 05:00:00',
               '2015-07-03 06:00:00', '2015-07-03 07:00:00'],
              dtype='datetime64[ns]', freq='H')

In [219]:
pd.period_range('2015-07', periods = 8, freq = 'M')

PeriodIndex(['2015-07', '2015-08', '2015-09', '2015-10', '2015-11', '2015-12',
             '2016-01', '2016-02'],
            dtype='period[M]', freq='M')

In [220]:
pd.timedelta_range(0, periods = 10, freq = 'D')

TimedeltaIndex(['0 days', '1 days', '2 days', '3 days', '4 days', '5 days',
                '6 days', '7 days', '8 days', '9 days'],
               dtype='timedelta64[ns]', freq='D')

In [221]:
pd.date_range('2015-07', periods= 8, freq = "M")

DatetimeIndex(['2015-07-31', '2015-08-31', '2015-09-30', '2015-10-31',
               '2015-11-30', '2015-12-31', '2016-01-31', '2016-02-29'],
              dtype='datetime64[ns]', freq='M')

In [222]:
pd.timedelta_range(0, periods = 9, freq = '2H30T')

TimedeltaIndex(['00:00:00', '02:30:00', '05:00:00', '07:30:00', '10:00:00',
                '12:30:00', '15:00:00', '17:30:00', '20:00:00'],
               dtype='timedelta64[ns]', freq='150T')

In [223]:
from pandas.tseries.offsets import BDay
pd.date_range('2015-07-03', periods = 5, freq = BDay())

DatetimeIndex(['2015-07-03', '2015-07-06', '2015-07-07', '2015-07-08',
               '2015-07-09'],
              dtype='datetime64[ns]', freq='B')

In [224]:
from pandas_datareader import data

ModuleNotFoundError: No module named 'pandas_datareader'